### ISSUE TITLE
React Performance Optimizations

### ISSUE THREAD

**Issue by tfromme** [tfromme/continuum-loot#28]
Convert to Classes and implement `shouldComponentUpdate` on many components.  See https://reactjs.org/docs/optimizing-performance.html    The earlier this gets done, the easier it will be.  This can also be done in many steps over time.

**Comment by ahartzog** [comment]
FYI @tfromme no need to convert to classes for this. Just export memo from react and wrap your export with it. This is the equivalent of declaring it as a pure component. It does the same shallow comparison of props to decide whether to re-render by default. 

You can also [provide a custom comparison function](https://dmitripavlutin.com/use-react-memo-wisely/#11-custom-equality-check-of-props) if you prefer.

![image](https://user-images.githubusercontent.com/9828263/94852225-8d751c80-03f7-11eb-8543-8bd41e53de7b.png)

**Comment by tfromme** [comment]
This could potentially be superseded by a refactor that includes less centralized data on the client side, doing more server side processing.  TBD

**Comment by tfromme** [comment]
Migrating to ReactTable and memoizing all the data there is sufficient for this
